#!/usr/bin/env bash

# TODO add printed warnings for missing cmds

# Source global definitions
[[ -f "/etc/bashrc" ]] && source /etc/bashrc


# ------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
export Color_Off='\033[0m'       # Text Reset

# Regular Colors
export Black='\033[0;30m'        # Black
export Red='\033[0;31m'          # Red
export Green='\033[0;32m'        # Green
export Yellow='\033[0;33m'       # Yellow
export Blue='\033[0;34m'         # Blue
export Purple='\033[0;35m'       # Purple
export Cyan='\033[0;36m'         # Cyan
export White='\033[0;37m'        # White

# Bold
export BBlack='\033[1;30m'       # Black
export BRed='\033[1;31m'         # Red
export BGreen='\033[1;32m'       # Green
export BYellow='\033[1;33m'      # Yellow
export BBlue='\033[1;34m'        # Blue
export BPurple='\033[1;35m'      # Purple
export BCyan='\033[1;36m'        # Cyan
export BWhite='\033[1;37m'       # White

# Underline
export UBlack='\033[4;30m'       # Black
export URed='\033[4;31m'         # Red
export UGreen='\033[4;32m'       # Green
export UYellow='\033[4;33m'      # Yellow
export UBlue='\033[4;34m'        # Blue
export UPurple='\033[4;35m'      # Purple
export UCyan='\033[4;36m'        # Cyan
export UWhite='\033[4;37m'       # White

# Background
export On_Black='\033[40m'       # Black
export On_Red='\033[41m'         # Red
export On_Green='\033[42m'       # Green
export On_Yellow='\033[43m'      # Yellow
export On_Blue='\033[44m'        # Blue
export On_Purple='\033[45m'      # Purple
export On_Cyan='\033[46m'        # Cyan
export On_White='\033[47m'       # White

# High Intensity
export IBlack='\033[0;90m'       # Black
export IRed='\033[0;91m'         # Red
export IGreen='\033[0;92m'       # Green
export IYellow='\033[0;93m'      # Yellow
export IBlue='\033[0;94m'        # Blue
export IPurple='\033[0;95m'      # Purple
export ICyan='\033[0;96m'        # Cyan
export IWhite='\033[0;97m'       # White

# Bold High Intensity
export BIBlack='\033[1;90m'      # Black
export BIRed='\033[1;91m'        # Red
export BIGreen='\033[1;92m'      # Green
export BIYellow='\033[1;93m'     # Yellow
export BIBlue='\033[1;94m'       # Blue
export BIPurple='\033[1;95m'     # Purple
export BICyan='\033[1;96m'       # Cyan
export BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
export On_IBlack='\033[0;100m'   # Black
export On_IRed='\033[0;101m'     # Red
export On_IGreen='\033[0;102m'   # Green
export On_IYellow='\033[0;103m'  # Yellow
export On_IBlue='\033[0;104m'    # Blue
export On_IPurple='\033[0;105m'  # Purple
export On_ICyan='\033[0;106m'    # Cyan
export On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------
# Bash options
# ------------------------------------------------------------------------------

setterm -linewrap on

# ------------------------------------------------------------------------------
# Bash history
# ------------------------------------------------------------------------------

shopt -s histappend

HISTFILE="$HOME/.bash_history_$( hostname )"

declare -a bash_history_dirs=(
    "$HOME/Syncthing/qed/bash_history"
    "$HOME/syncthing/qed/bash_history"
    "$HOME/.syncthing/qed/bash_history"
    "$HOME/Sync/qed/bash_history"
    "$HOME/sync/qed/bash_history"
    "$HOME/.sync/qed/bash_history"
)

for bhd in "${bash_history_dirs[@]}"; do
    if [[ -d "${bhd}" ]]; then
        HISTFILE="${bhd}/.bash_history_$( hostname )"
    fi
done

HISTFILESIZE=500
HISTSIZE=500
export HISTTIMEFORMAT='%F %T ' # Same as '%Y-%m-%d %H:%M:%S '

# Immediately add commands to your history instead of waiting for the end of each session.
# First, you need to append to the history file immediately with history -a.
# Next, you must clear the current history in your shell session with history -c.
# Finally, to load the updated history back into your shell session, use the history -r command.
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# ------------------------------------------------------------------------------
# Session Variables
# ------------------------------------------------------------------------------
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
export XDG_STATE_HOME="$HOME/.local/state" # for flatpak mpv
export MOZ_ENABLE_WAYLAND=1
export PAGER="less"

# ------------------------------------------------------------------------------
# PATH
# ------------------------------------------------------------------------------

# PATH uses first-come-first-served approach,
# so add items to end of PATH if you want
# to prevent system commands being overridden.

# mapfile -t original_PATH_paths < <( echo "${PATH//:/$'\n'}" )

declare -a additional_PATH_paths=(
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    "$HOME/.scripts"
    "$HOME/.scripts/cts"
    "/home/linuxbrew/.linuxbrew/opt/rustup/bin"
)

for aPp in "${additional_PATH_paths[@]}"; do
    PATH="${aPp}:$PATH"
    # if [[ -d "${aPp}" ]]; then
    #     PATH=$( find "${aPp}" -type d -not -path '*.git*' -printf "%p:" )$PATH
    # fi
done

# Remove any duplicates
# https://unix.stackexchange.com/a/40755
PATH="$( printf %s "$PATH" | awk -v RS=: -v ORS=: '!arr[$0]++' )"

export PATH

# ------------------------------------------------------------------------------
# PYTHONPATH
# ------------------------------------------------------------------------------

declare -a additional_PYTHONPATH_paths=(
    "$HOME/.scripts"
    "/usr/bin"
)

for aPPp in "${additional_PYTHONPATH_paths[@]}"; do
    PYTHONPATH="${aPPp}:$PYTHONPATH"
done

# Remove any duplicates
PYTHONPATH="$( printf %s "$PYTHONPATH" | awk -v RS=: -v ORS=: '!arr[$0]++' )"

export PYTHONPATH

# ------------------------------------------------------------------------------
# Homebrew
# ------------------------------------------------------------------------------

if command -v brew &> /dev/null; then
    eval "$($( brew --prefix )/bin/brew shellenv)"
elif [[ -e "/home/linuxbrew/.linuxbrew/bin/brew" ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" &> /dev/null
fi
HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/home/linuxbrew/.linuxbrew}"

# ------------------------------------------------------------------------------
# Other exports
# ------------------------------------------------------------------------------

if command -v code &> /dev/null ; then
    export VISUAL="code --wait"
fi

if command -v nano &> /dev/null ; then
    export EDITOR="nano"
fi

if command -v moor &> /dev/null ; then
    export PAGER="moor"
    export MOOR='--statusbar=bold --no-linenumbers'
fi

# ------------------------------------------------------------------------------
# Functions & Aliases
# ------------------------------------------------------------------------------

# Expand aliases with Ctrl+Space
bind -x '"\C- ": alias-expand-line'
# Always expand aliases
# shopt -s expand_aliases

function path_print_as_list {
    echo "${PATH//:/$'\n'}"
}
alias lspath='print_path_as_list'

# ------------------------------------------------------------------------------

# You can use the bash(1) built-in compgen:
#   compgen -c                  will list all the commands you could run.
#   compgen -a                  will list all the aliases you could run.
#   compgen -b                  will list all the built-ins you could run.
#   compgen -k                  will list all the keywords you could run.
#   compgen -A function         will list all the functions you could run.
#   compgen -A function -abck   will list all the above in one go.
# Check the man page for other completions you can generate.
# To list & search e.g. all available commands and aliases:
#   compgen -ac PATTERN

function r { (
    set ${SET_X:+-x} -eou pipefail
    compgen -A function -abck | fzf
); }

function ra { (
    set ${SET_X:+-x} -eou pipefail
    compgen -a | fzf
); }

function rf { (
    set ${SET_X:+-x} -eou pipefail
    compgen -A function | fzf
); }

alias sudo='sudo ' # keep aliases, https://unix.stackexchange.com/a/349290

# Use sudo on functions and aliases
# https://unix.stackexchange.com/a/438712
function sudoaf {
    local firstArg=$1
    if [ $(type -t $firstArg) = function ]
    then
        shift && command sudo bash -c "$(declare -f $firstArg);$firstArg $*"
    elif [ $(type -t $firstArg) = alias ]
    then
        alias sudo='\sudo '
        eval "sudo $@"
    else
        command sudo "$@"
    fi
}

# https://commandmasters.com/commands/systemd-inhibit-linux/
# https://man.archlinux.org/man/systemd-inhibit.1
# https://kd8bny.com/posts/session_inhibit/
alias inhibit='systemd-inhibit --no-ask-password --what=idle --who="$USER" --why="Obvious reasons..."'

# run in the background & inhibit
function rib { (
    set ${SET_X:+-x} -eou pipefail
    systemd-inhibit --no-ask-password --what=idle --who="$USER" --why="Obvious reasons..." $@ & disown
    if [[ ! -v INHIBIT_PID_LIST ]]; then
        declare -a INHIBIT_PID_LIST=()
    fi
    export INHIBIT_PID_LIST+=( "$!" )
); }

# inhibit_no_more
function ribz { (
    set ${SET_X:+-x} -eou pipefail
    if [[ ! -v INHIBIT_PID_LIST ]]; then
        printf '%s\n' "No background PIDs found."
    else
        mapfile -t selected_pids < <( printf '%s\n' "${INHIBIT_PID_LIST[@]}" | fzf --multi )
        for INHIBIT_PID in "${selected_pids[@]}"; do
            kill -SIGKILL "${INHIBIT_PID}"

            # Loop through original pids, put all not matching killed pid in new array, replace pid array with new.
            declare -a INHIBIT_PID_LIST_NEW=()
            for pid in "${INHIBIT_PID_LIST[@]}"; do
                if [[ "${pid}" != "${INHIBIT_PID}" ]]; then
                    INHIBIT_PID_LIST_NEW+=( "${pid}" )
                fi
            done
            export INHIBIT_PID_LIST+=("${INHIBIT_PID_LIST_NEW[@]}")
            unset INHIBIT_PID_LIST_NEW

        done
    fi
); }

# ------------------------------------------------------------------------------

alias linger="loginctl enable-linger $USER"

# A set of smooth, fzf-powered shell aliases & functions for systemctl
# https://silverrainz.me/blog/2025-09-systemd-fzf-aliases.html

# Simple aliases.
alias s='sudo systemctl'
alias sj='journalctl'
alias u='systemctl --user'
alias uj='journalctl --user'

# SystemD unit selector.
function _sysls {
    # $1: --system or --user
    # $2: states, see also "systemctl list-units --state=help"
    WIDE=$1
    [ -n $2 ] && STATE="--state=$2"
    \cat \
        <( echo 'UNIT/FILE LOAD/STATE ACTIVE/PRESET SUB DESCRIPTION' ) \
        <( \systemctl $WIDE list-units --legend=false $STATE ) \
        <( \systemctl $WIDE list-unit-files --legend=false $STATE ) \
    | \sed 's/●/ /' \
    | \grep . \
    | \column --table --table-columns-limit=5 \
    | \fzf --header-lines=1 \
        --accept-nth=1 \
        --no-hscroll \
        --preview="SYSTEMD_COLORS=1 systemctl $WIDE status {1}" \
        --preview-window=down
}

# Aliases for unit selector.
alias sls='_sysls --system'
alias uls='_sysls --user'
alias sjf='sj --unit $(uls) --all --follow'
alias ujf='uj --unit $(uls) --all --follow'

_SYS_ALIASES=(
    sstart sstop sre
    ustart ustop ure
)
_SYS_CMDS=(
    's start $(sls static,disabled,failed)'
    's stop $(sls running,failed)'
    's restart $(sls)'
    'u start $(uls static,disabled,failed)'
    'u stop $(uls running,failed)'
    'u restart $(uls)'
)

function _sysexec {
    for ((j=0; j < ${#_SYS_ALIASES[@]}; j++)); do
        if [ "$1" == "${_SYS_ALIASES[$j]}" ]; then
            cmd=$(eval echo "${_SYS_CMDS[$j]}") # expand service name
            wide=${cmd:0:1}
            cmd="$cmd && ${wide} status \$_ || ${wide}j -xeu \$_"
            eval $cmd

            # Push to history.
            [ -n "$BASH_VERSION" ] && history -s $cmd
            [ -n "$ZSH_VERSION" ] && print -s $cmd
            return
        fi
    done
}

# Generate bash function/zsh widgets.
for i in ${_SYS_ALIASES[@]}; do
    source /dev/stdin <<EOF
$i() {
    _sysexec $i
}
EOF
done

# ------------------------------------------------------------------------------

alias jfs="journalctl --follow --unit"
alias jfu="journalctl --follow --user-unit"

# https://github.com/walles/px#killing-processes
alias pxk="px --sort=cpupercent | fzf --bind 'ctrl-r:reload(px --sort=cpupercent)' --height=20 --no-hscroll --tac --no-sort --header-lines=1 | awk '{print $1}' | xargs kill -9"
alias pxkp="px --sort=cpupercent --no-username | fzf --preview='px --color {1}' --bind 'ctrl-r:reload(px --sort=cpupercent --no-username)' --height=20 --no-hscroll --tac --no-sort --header-lines=1 | awk '{print $1}' | xargs kill -9"

# ------------------------------------------------------------------------------

alias c="clear"
alias clean="clear"

alias t='tmux new-session -A'
alias ta='tmux new-session -A'
alias ts='tmux-select-sessions'
alias tr='reset; tmux clear-history'

# ------------------------------------------------------------------------------

alias ~="cd ~"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Frequently used paths
alias 1='cd ~/Downloads'
alias 2='cd ~/syncthing/qed'
alias 3='cd ~/rfs/nasgard/nas'

# Workspace manager
alias ws='cd ~/workspace/$( \ls ~/workspace | fzf )'
function _wsnew { (
    set ${SET_X:+-x} -eou pipefail
    fn="$(date +%Y-%m)_$1" # TODO Check input
    mkdir -p ~/workspace/$fn
    cd ~/workspace/$fn
); }
alias wsnew='_wsnew'

alias ls="ls -1a --color=auto"
alias lsl="ls -lha --color=auto"

if command -v eza 2>&1 >/dev/null; then
    # https://gist.github.com/AppleBoiy/04a249b6f64fd0fe1744aff759a0563b
    alias _eza='eza --color=always --group-directories-first --icons --classify=always --all --hyperlink --mounts'
    alias l='_eza -1'
    alias l1='_eza -1'
    alias ll='_eza --long --header --smart-group' # display extended file metadata as a table
    alias lll="_eza --long --header --group --created --accessed --modified --time-style='+%F %T %z '"
    alias llll="_eza --long --header --group --created --accessed --modified --time-style='+%F %T %z ' --links --context"

    alias lg='l1 --git' # list each file's Git status, if tracked or ignored

    alias lod='l1 --only-dirs'
    alias l1od='l1 --only-dirs'
    alias lof='l1 --only-files'
    alias l1of='l1 --only-files'

    alias ldot='l1 -d .*'
    alias l.='l1 -d .*'

    alias ltd='_eza --tree'
    alias lts='_eza --tree --level=2'
fi

alias o='xdg-open'
alias tsh='trash' # use trash rather than rm

if command -v mkd 2>&1 >/dev/null; then
    # Make new directory and move to it
    function mkdcd { (
        set ${SET_X:+-x} -eou pipefail
        cd -- "$( mkd -d "$*" )"
    ); }
fi

if command -v expand_path 2>&1 >/dev/null; then
    function lns { (
        set ${SET_X:+-x} -eou pipefail
        # -s, --symbolic        make symbolic links instead of hard links
        # -i, --interactive     prompt whether to remove destinations
        # -n, --no-dereference  treat LINK_NAME as a normal file if it is a symbolic link to a directory
        # -v, --verbose         print name of each linked file
        [[ $# == 2 ]] && ln -sinv "$( expand_path "${1}" )" "$( expand_path "${2}" )"
    ); }
fi

alias cp="cp -vai"
alias mv="mv -vi"
alias rm="rm -vr"
alias mkdir="mkdir -vp"

alias untar="tar -xJf"

alias diff="difft" # difftastic, syntax-aware diffing
# alias diff="delta" # git-delta

# ------------------------------------------------------------------------------

# alias f='yazi'

# Superfile terminal file manager 'cd_on_quit' | https://superfile.dev/
if command -v spf 2>&1 >/dev/null; then
    function f { (
        set ${SET_X:+-x} -eou pipefail
        export SPF_LAST_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/superfile/lastdir"

        command spf "$@"

        [ ! -f "$SPF_LAST_DIR" ] || {
            . "$SPF_LAST_DIR"
            rm -f -- "$SPF_LAST_DIR" > /dev/null
        }
    ); }
fi

# nnn with autocd on exit
if command -v nnn 2>&1 >/dev/null; then
    function n {
        # Block nesting of nnn in subshells
        [ "${NNNLVL:-0}" -eq 0 ] || {
            echo "nnn is already running"
            return
        }

        # The behaviour is set to cd on quit (nnn checks if NNN_TMPFILE is set)
        # If NNN_TMPFILE is set to a custom path, it must be exported for nnn to
        # see. To cd on quit only on ^G, remove the "export" and make sure not to
        # use a custom path, i.e. set NNN_TMPFILE *exactly* as follows:
        #      NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
        export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

        # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
        # stty start undef
        # stty stop undef
        # stty lwrap undef
        # stty lnext undef

        # The command builtin allows one to alias nnn to n, if desired, without
        # making an infinitely recursive alias
        command nnn "$@"

        [ ! -f "$NNN_TMPFILE" ] || {
            source "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
        }
    }
fi

# ------------------------------------------------------------------------------

alias grep='grep --color=auto'
alias g='grep --color=auto -r'
function hlt { (
    set ${SET_X:+-x} -eou pipefail
    grep --color=always -E "${1}|$"
); }

if command -v ug 2>&1 >/dev/null; then
    alias uge='ug -E'
    alias ugf='ug -F' # search for matching strings, not regex patterns, like GNU fgrep or grep -F
    alias ugz='ug -z' # recursively search for files, archives and compressed files matching PATTERN
    alias ugze='ug -zE'
    alias ugzf='ug -zF'
fi

# ------------------------------------------------------------------------------

if command -v git 2>&1 >/dev/null; then
    alias gl='git log --color --graph --decorate -M --pretty=oneline --abbrev-commit -M'
    alias gp='git push'
    alias gpl='git pull'
    alias gf='git fetch'
    alias gs='git status'
    alias ga='git add'
    alias gd='git diff'
    alias gcm='git commit'
    alias gco='git checkout'
    alias gst='git stash'
    alias grs='git restore --staged'
    alias gr='cd $(git rev-parse --show-toplevel)' # cd to git root
    alias gg='git grep'
fi

# ------------------------------------------------------------------------------

alias gen_ssh='ssh-keygen -t ed25519 -C "${USER}@$(hostname)"'
alias ssh_gen='gen_ssh'
alias sshgen='gen_ssh'

# https://jordanelver.co.uk/blog/2010/11/27/automatically-attaching-to-a-tmux-session-via-ssh/
# servername="ssh servername -t tmux a"

# ------------------------------------------------------------------------------

alias dns-flush="sudo resolvectl flush-caches"
alias flush-dns="dns-flush"
alias dns-refresh="dns-flush"
alias refresh-dns="dns-flush"

function lsip { (
    set ${SET_X:+-x} -eou pipefail
    printf "[${BPurple}WAN${Color_Off}]\n%s\n" "$( curl -s https://icanhazip.com || curl -s https://ifconfig.me || curl -s https://ipecho.net/plain || curl -s ipinfo.io/ip || wget -qO- https://icanhazip.com || wget -qO- https://ifconfig.me )"
    printf "[${BPurple}LAN${Color_Off}]\n%s\n%s\n" "$( ip -c -h -brief address show )" "$( ip -c -h -brief link show )"
); }

alias lsnic="lsip"
alias lsnet="lsip"

# Show visible port identification (e.g. blinking)
alias idnic="ethtool -p" # ethtool [ FLAGS ] -p|--identify DEVNAME [ TIME-IN-SECONDS ]
alias idnif='idnic'
alias idif='idnic'
alias idport='idnic'

if command -v nmcli 2>&1 >/dev/null; then
    alias nmls="nmcli dev show"
fi

# ------------------------------------------------------------------------------

if command -v chezmoi 2>&1 >/dev/null; then
    alias czm="chezmoi"
    alias czmi="chezmoi init"
    alias czma="chezmoi apply"
    function chezmoi-rerun-scripts { (
        set ${SET_X:+-x} -eou pipefail
        chezmoi state delete-bucket --bucket=entryState
        chezmoi state delete-bucket --bucket=scriptState
        # rm -f "${HOME}/.config/chezmoi/chezmoistate.boltdb"
        chezmoi init --apply
    ); }
fi

if command -v btop 2>&1 >/dev/null; then
    alias b="btop"
fi

if command -v bat 2>&1 >/dev/null; then
    alias bat='bat --style=plain --pager=never'
fi

# ------------------------------------------------------------------------------

function gen_pass {
    [[ -v 1 ]] && length=$1 || length=32
    </dev/urandom tr -dc '1234567890qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM!$%^&*@~#<>?\|/' | head -c $length ; echo ""
}
alias genpass='gen_pass'
alias passgen='gen_pass'

# ------------------------------------------------------------------------------

if command -v apt 2>&1 >/dev/null; then
    alias aptli="apt list --installed"
fi

if command -v dnf 2>&1 >/dev/null; then
    alias dnfli="dnf list --installed"
fi

if command -v rpm 2>&1 >/dev/null; then
    alias rpmli="rpm -qa | sort"
fi

if command -v flatpak 2>&1 >/dev/null; then
    alias flatpaklrs="flatpak remotes --columns=name"
    alias flatpaklru="flatpak remotes --user --columns=name"
    alias flatpaklis="flatpak list --columns=application"
    alias flatpakliu="flatpak list --user --columns=application"
fi

if command -v brew 2>&1 >/dev/null; then
    alias brewlt="brew tap"
    alias brewlf="brew list --formula -1"
fi

if command -v pip 2>&1 >/dev/null; then
    alias pipls="pip list"
fi

if command -v pipx 2>&1 >/dev/null; then
    alias pipxls="pipx list --short"
fi

if command -v code 2>&1 >/dev/null; then
    alias codels="code --list-extensions"
fi

if command -v gext 2>&1 >/dev/null; then
    alias gextls="gext list -a"
fi

# ------------------------------------------------------------------------------

if command -v docker 2>&1 >/dev/null; then
    alias docker-gc="docker system prune --force"
fi

# ------------------------------------------------------------------------------

alias secureboot-status='mokutil --sb-state'
alias secure-boot-status='mokutil --sb-state'

# ------------------------------------------------------------------------------

alias py="python"

# ------------------------------------------------------------------------------

alias serve="python3 -m http.server 33333"

if command -v miniserve 2>&1 >/dev/null; then
    function miniserve { (
        set ${SET_X:+-x} -eou pipefail
        \miniserve -p 33333 --pretty-urls --no-symlinks --enable-tar-gz --enable-zip --dirs-first --show-wget-footer "${1:-$( pwd )}"
    ); }
elif command -v podman 2>&1 >/dev/null; then
    function miniserve { (
        set ${SET_X:+-x} -eou pipefail
        podman run \
            --rm -it \
            -v "${1:-$( pwd )}":/tmp \
            -p 33333:8080 \
            docker.io/svenstaro/miniserve \
            --pretty-urls --no-symlinks \
            --enable-tar-gz --enable-zip \
            --dirs-first --show-wget-footer \
            /tmp
    ); }
elif command -v docker 2>&1 >/dev/null; then
    function miniserve { (
        set ${SET_X:+-x} -eou pipefail
        docker run \
            --rm -it \
            -v "${1:-$( pwd )}":/tmp \
            -p 33333:8080 \
            docker.io/svenstaro/miniserve \
            --pretty-urls --no-symlinks \
            --enable-tar-gz --enable-zip \
            --dirs-first --show-wget-footer \
            /tmp
    ); }
fi

function copyparty {
    docker run \
        --rm \
        -it \
        --label com.centurylinklabs.watchtower.enable=true \
        -u 1000 \
        -p 33923:3923 \
        -v "$( pwd )":/w:z \
        -v $HOME/.config/copyparty:/cfg:z \
        -e LD_PRELOAD=/usr/lib/libmimalloc-secure.so.2 \
        copyparty/dj \
        -v /w::r
}

# ------------------------------------------------------------------------------
# aliases from justfiles
# https://just.systems/man/en/chapter_73.html#global-and-user-justfiles
# ------------------------------------------------------------------------------

if command -v just 2>&1 >/dev/null; then

    # Aliases from other user justfiles ala `just --global-justfile`
    declare -a justfiles=(
        "$HOME/.config/just/justfile"
        "$HOME/.justfile"
    )

    for jf in "${justfiles[@]}"; do
        if [[ -f "${jf}" ]]; then
            for recipe in `just --justfile "${jf}" --summary`; do
                alias $recipe="just --justfile ${jf} --working-directory . $recipe"
            done
        fi
    done

    unset justfiles
fi

# ------------------------------------------------------------------------------
# Other user specific aliases and functions
# ------------------------------------------------------------------------------
# if [[ -d "$HOME/.bashrc.d" ]]; then
#     mapfile -t bashrc_d_f < <( find "$HOME/.bashrc.d" -type f )
#     for rc in "${bashrc_d_f[@]}"; do
#         if [[ -f "${rc}" ]]; then
#             source "${rc}"
#         fi
#     done
#     unset rc bashrc_d_f
# fi

# declare -a cmds=( nmcli docker )
# # Setup aliases if commands exist
# for cmd in "${cmds[@]}"; do
#     command -v "$cmd" >/dev/null && {
#         case "$cmd" in
#             nmcli)  alias lsnm="nmcli dev show";;
#             docker) alias docker-gc="docker system prune --force";;
#         esac
#     }
# done
# unset cmds

# ------------------------------------------------------------------------------
# bash-preexec.sh
# ------------------------------------------------------------------------------

declare -a bash_preexec_locations=(
    "/etc/profile.d/bash-preexec.sh"
    "/usr/share/bash-prexec"
    "/usr/share/bash-prexec.sh"
    "${HOMEBREW_PREFIX}/etc/profile.d/bash-preexec.sh"
)

for bpl in "${bash_preexec_locations[@]}"; do
    if [[ -f "${bpl}" ]]; then
        source "${bpl}"
        break
    fi
done

unset bash_preexec_locations

# ------------------------------------------------------------------------------
# Use bash-completion, if available
# ------------------------------------------------------------------------------

if ! shopt -oq posix; then

    declare -a bash_completion_locations=(
        "/usr/share/bash-completion/bash_completion"
        "/etc/bash_completion"
    )

    for bcl in "${bash_completion_locations[@]}"; do
        if [[ -f "${bcl}" ]]; then
            source "${bcl}"
            break
        fi
    done

    unset bash_completion_locations

fi

# ------------------------------------------------------------------------------

[ "$(command -v fzf)" ] && eval "$(fzf --bash)"
[ "$(command -v starship)" ] && eval "$(starship init bash)"
[ "$(command -v thefuck)" ] && eval "$(thefuck --alias)"
[ "$(command -v carapace)" ] && source <(carapace _carapace)
[ "$(command -v zoxide)" ] && eval "$(zoxide init bash)"

# ------------------------------------------------------------------------------
# Set directory for new shells on Termux
# ------------------------------------------------------------------------------

[[ "$( uname -a )" =~ 'Android' && -d "${HOME}/storage/downloads" ]] && cd "${HOME}/storage/downloads"
