#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "podman" "openssl" "expand_path" )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

app_name="comfyui"
base_image="docker.io/rocm/comfyui:comfyui-0.18.2.amd0_rocm7.2.0_ubuntu24.04"

read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" data_location

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
mkdir -pv "$HOME/.config/containers/systemd"
mkdir -pv "$( expand_path "${data_location}" )"{/models,/output,/settings,/workflows,/tls,/custom_nodes}
# mkdir -pv "${data_location}"{/models{/diffusion_models,/unet,/vae,/text_encoders,/clip,/checkpoints,/lora},/output,/settings,/workflows,/tls,/custom_nodes}

[[ ! -f "${data_location}/tls/key.pem" || ! -f "${data_location}/tls/cert.pem" ]] && openssl req -x509 -newkey rsa:4096 -keyout "${data_location}/tls/key.pem" -out "${data_location}/tls/cert.pem" -sha256 -days 3650 -nodes -subj "/C=CU/ST=${app_name}/L=${app_name}/O=${app_name}/OU=${app_name}/CN=${app_name}"

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"

ENTRYPOINT='
# --- Prepare custom nodes ---
CN_DIR=/app/ComfyUI/custom_nodes
INIT_MARKER="$CN_DIR/.custom_nodes_initialized"

declare -A REPOS=(
    # ["ComfyUI-Manager"]="https://github.com/ltdrdata/ComfyUI-Manager.git"
    # ["ComfyUI_essentials"]="https://github.com/cubiq/ComfyUI_essentials.git"
    ["ComfyUI-Crystools"]="https://github.com/crystian/ComfyUI-Crystools.git"
    ["rgthree-comfy"]="https://github.com/rgthree/rgthree-comfy.git"
    ["ComfyUI-KJNodes"]="https://github.com/kijai/ComfyUI-KJNodes.git"
    ["ComfyUI_UltimateSDUpscale"]="https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git"

    # WorkFlow for Flux.dev by Danrisi (txt2img, img2img, upscale and some QoL stuff)
    # https://civitai.com/models/1662914/workflow-for-fluxdev-by-danrisi-txt2img-img2img-upscale-and-some-qol-stuff
    ["ComfyUI-Custom-Scripts"]="https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git"
    ["ComfyUI-GGUF"]="https://github.com/city96/ComfyUI-GGUF.git"
    ["CG Use Everywhere"]="https://github.com/chrisgoringe/cg-use-everywhere.git"
    ["ControlAltAI_Nodes"]="https://github.com/gseth/ControlAltAI-Nodes.git"
    ["Image Size Tool"]="https://github.com/TheLustriVA/ComfyUI-Image-Size-Tools.git"
    ["ComfyUI Impact Pack"]="https://github.com/ltdrdata/ComfyUI-Impact-Pack.git"
    ["ComfyUI-GGUF-FantasyTalking"]="https://github.com/kael558/ComfyUI-GGUF-FantasyTalking.git"
)

if [ ! -f "$INIT_MARKER" ]; then
    echo "↳ First run: initializing custom_nodes…"
    mkdir -p "$CN_DIR"
    for name in "${!REPOS[@]}"; do
        url="${REPOS[$name]}"
        target="$CN_DIR/$name"
        if [ -d "$target" ]; then
        echo "  ↳ $name already exists, skipping clone"
        else
        echo "  ↳ Cloning $name"
        git clone --depth 1 "$url" "$target"
        fi
    done

    echo "↳ Installing/upgrading dependencies…"
    for dir in "$CN_DIR"/*/; do
        req="$dir/requirements.txt"
        if [ -f "$req" ]; then
        echo "  ↳ pip install --upgrade -r $req"
        python -m pip install --no-cache-dir --upgrade -r "$req"
        fi
    done

    # Create marker file
    touch "$INIT_MARKER"
else
    echo "↳ Custom nodes already initialized, skipping clone and dependency installation."
fi

echo "↳ Launching ComfyUI"
exec "$@"
'
echo "${ENTRYPOINT}" | tee "${data_location}/${app_name}.entrypoint" > /dev/null

CONTAINERFILE="
FROM ${base_image}

# Copy and enable the startup script
# COPY ${data_location}/${app_name}.entrypoint /entrypoint.sh
# RUN chmod +x /entrypoint.sh

# Expose the port that ComfyUI will use (change if needed)
EXPOSE 8188

# Run entrypoint first, then start ComfyUI
# ENTRYPOINT ["/entrypoint.sh"]
CMD ["python","/workload/ComfyUI/main.py","--tls-keyfile","/workload/ComfyUI/tls/key.pem","--tls-certfile","/workload/ComfyUI/tls/cert.pem","--port","8188","--listen","0.0.0.0"]
"
echo "${CONTAINERFILE}" | tee "$HOME/.config/containers/systemd/${app_name}.Containerfile" > /dev/null

BUILD="
[Build]
ImageTag=localhost/${app_name}:latest
File=${app_name}.Containerfile
SetWorkingDirectory=unit
"
echo "${BUILD}" | tee "$HOME/.config/containers/systemd/${app_name}.build" > /dev/null

CONTAINER="
[Unit]
Description=${app_name} quadlet
After=network-online.target

[Container]
ContainerName=${app_name}
Image=${app_name}.build
PublishPort=8188:8188
SeccompProfile=unconfined
AddCapability=SYS_PTRACE
AddDevice=/dev/kfd
AddDevice=/dev/dri
GroupAdd=video
# AutoUpdate=registry

# persist your tls certs:
Volume=${data_location}/tls:/workload/ComfyUI/tls:Z
# persist your models:
Volume=${data_location}/models:/workload/ComfyUI/models:Z
# persist your custom nodes:
Volume=${data_location}/custom_nodes:/workload/ComfyUI/custom_nodes:Z
# persist your output images:
Volume=${data_location}/output:/workload/ComfyUI/output:Z
# persist all your settings & extra nodes:
Volume=${data_location}/settings:/workload/ComfyUI/user/default:Z
# persist just your saved flows (overrides the workflows/ in default):
Volume=${data_location}/workflows:/workload/ComfyUI/user/default/workflows:Z

# Networking: Pasta is used by default in Podman 5+
# If you need to access host services (like Ollama on the host):
AddHost=host.containers.internal:host-gateway

[Service]
Restart=always
RestartSec=5
# Give image pulls/builds enough time during startup
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target default.target
"
echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null

printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
systemctl --user daemon-reload

printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
systemctl --user restart "${app_name}"

# Start user services even when not logged in
loginctl enable-linger $USER

printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
# manually by calling 'podman auto-update'
# or automatically by enabling the relative systemd service:
systemctl enable --user --now podman-auto-update.timer
