#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "podman" "expand_path"  )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - '${rc}' not available!"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

REMOVE="false"

usage() {
    echo "Usage: ${executor} [-h] [-v]" >&2
}

while getopts ":rh" opt; do
    case $opt in
        r) REMOVE="true" ;;
        h) usage; exit 0 ;;
        \?) usage; exit 1 ;;
        :) usage; exit 1 ;;
    esac
done

shift $((OPTIND - 1))

app_name="lemonade"

if [[ "${REMOVE}" == "true" ]]; then

    if [[ "$( podman version --format '{{.Client.Version}}' | cut -d '.' -f 1 )" -gt "5" ]]; then
        # --force, -f
        # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
        # --ignore, -i
        # Do not error for Quadlets that do not exist.
        # --recursive
        # Required when removing applications (default false).
        podman quadlet rm --force --ignore --recursive -- "${app_name}"
    else

        [[ "$( systemctl --user is-active "quadlet-${app_name}" )" == "active" ]] && systemctl --user stop "quadlet-${app_name}"

        printf "[${executor}] ${BPurple}INFO${Color_Off} - Remove quadlet container files...\n"
        rm -fv "$HOME/.config/containers/systemd/quadlet-${app_name}".*

        printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
        systemctl --user daemon-reload

        printf "[${executor}] ${BPurple}INFO${Color_Off} - Remove quadlet init files...\n"
        rm -rfv "$HOME/.config/quadlets/init/${app_name}"

    fi

else

    read -e -p "Enter config location: " -i "$HOME/.config/quadlets/data/${app_name}" config_location
    config_location="$( expand_path "${config_location}" )"

    # $( whoami ) or $( id -un ) for current user
    read -e -p "UID: " -i "$( id -u )" local_user_uid # or $( id -u <username> ) for any other user than current
    read -e -p "GID: " -i "$( id -g )" local_user_gid # or $( id -g <username> ) for any other user than current

    echo
    printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
    mkdir -pv "$HOME/.config/containers/systemd"
    mkdir -pv "$HOME/.config/quadlets/init/${app_name}"
    mkdir -pv "${config_location}"{/cache,/llama,/recipe}

    echo
    printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
    CONTAINER="
[Unit]
Description=${app_name} quadlet
Wants=network-online.target
After=network-online.target
# Limit to 5 restart attempts within a 60 second window
StartLimitIntervalSec=60
StartLimitBurst=5

[Container]
ContainerName=${app_name}
Image=ghcr.io/lemonade-sdk/lemonade-server:latest
PublishPort=13305:13305
# PublishPort=9000:9000
Volume=${config_location}/cache:/opt/lemonade/.cache/huggingface:Z,U
Volume=${config_location}/llama:/opt/lemonade/llama:Z,U
Volume=${config_location}/recipe:/opt/lemonade/.cache/lemonade:Z,U
AddDevice=-/dev/kfd
AddDevice=-/dev/dri
AutoUpdate=registry
GroupAdd=video
SecurityLabelDisable=true

# User=10001:10001
# User Namespace: Maps container user to host user
# UserNS=keep-id:uid=${local_user_uid},gid=${local_user_gid}

# Networking: Pasta is used by default in Podman 5+
# If you need to access host services (like Ollama on the host):
# AddHost=host.containers.internal:host-gateway

[Service]
Restart=always
RestartSec=5
# Give image pulls/builds enough time during startup
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target default.target
"
    echo "${CONTAINER}" | tee "$HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}.container" > /dev/null

# sh -c "cat > $HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}-cache.volume" << 'EOF'
# [Volume]
# EOF
# sh -c "cat > $HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}-llama.volume" << 'EOF'
# [Volume]
# EOF
# sh -c "cat > $HOME/.config/quadlets/init/${app_name}/quadlet-${app_name}-recipe.volume" << 'EOF'
# [Volume]
# EOF

#     ROCM_CONFIG='
# {
#     "llamacpp": {
#         "backend": "rocm"
#     }
# }
# '
#     [[ ! -d "${config_location}/recipe" ]] && mkdir -pv "${config_location}/recipe"
#     echo "${ROCM_CONFIG}" | tee "${config_location}/recipe/config.json" > /dev/null

    printf "[${executor}] ${BPurple}INFO${Color_Off} - Installing quadlet...\n"
    if [[ "$( podman version --format '{{.Client.Version}}' | cut -d '.' -f 1 )" -gt "5" ]]; then
        podman quadlet install --replace --application "${app_name}" -- "$HOME/.config/quadlets/init/${app_name}/"
    else
        \cp -v "$HOME/.config/quadlets/init/${app_name}/"* "$HOME/.config/containers/systemd/"

        printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
        systemctl --user daemon-reload

        printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
        systemctl --user restart "quadlet-${app_name}"
    fi

    # Start user services even when not logged in
    loginctl enable-linger $USER

    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
    # manually by calling 'podman auto-update'
    # or automatically by enabling the relative systemd service:
    systemctl enable --user --now podman-auto-update.timer
fi
