#!/usr/bin/env -S uv run --script
#
# /// script
# dependencies = [
#   "validators",
#   "click",
#   "rich",
# ]
# ///

import sys

import click
import validators
from rich import print as rp


@click.command()
@click.option("-v", "--verbose", "verbose", is_flag=True, default=False)
@click.argument("inputs", nargs=-1)
def str_valid_ip_or_hostname(verbose: bool, inputs: tuple[str, ...]):
    fail: bool = False
    for input in inputs:
        if not validators.hostname(input, may_have_port=False):
            if verbose:
                rp(f"[default]{input}[/default] -> [bold red]INVALID[/bold red]")
            fail = True
        else:
            if verbose:
                rp(f"[default]{input}[/default] -> [bold green]VALID[/bold green]")
    if fail:
        sys.exit(1)


if __name__ == "__main__":
    str_valid_ip_or_hostname()
