#!/usr/bin/env python

import argparse


def str_replace():

    parser = argparse.ArgumentParser(
        description="Replace given part of input string(s) with provided replacement.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-t",
        "--targets",
        type=str,
        nargs="+",
        help="The character(s) or string(s) to target.",
    )

    parser.add_argument(
        "-r",
        "--replacement",
        required=True,
        type=str,
        help="The character or string to use as the replacement.",
    )

    parser.add_argument(
        "-c",
        "--count",
        default=-1,
        type=int,
        help="Number of occurrences to replace.",
    )

    parser.add_argument(
        "inputs",
        metavar="I",
        type=str,
        nargs="+",
        help="Strings to process.",
    )

    args = parser.parse_args()

    for input in args.inputs:
        output: str = input
        for target in args.targets:
            output: str = output.replace(target, args.replacement, args.count)
        print(output)


if __name__ == "__main__":
    str_replace()
