#!/usr/bin/env python

import argparse


def str_replace():

    parser = argparse.ArgumentParser(
        description="Replace given part of input string(s) with provided replacement.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "-t",
        "--target",
        required=True,
        type=str,
        help="The character or string to target.",
    )

    parser.add_argument(
        "-r",
        "--replacement",
        required=True,
        type=str,
        help="The character or string to use as the replacement.",
    )

    parser.add_argument(
        "strings",
        metavar="S",
        type=str,
        nargs="+",
        help="Strings to join.",
    )

    args = parser.parse_args()

    for input in args.strings:
        print(input.replace(args.target, args.replacement))


if __name__ == "__main__":
    str_replace()
