#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "gum" "fd" "expand_path" "str_replace_part" )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - Command '${rc}' unavailable!?"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

function rfs_usage {

}

function rfs_add {
    local server_name="$( gum input --placeholder "server_name?" )"

    while :; do
        local server_address="$( gum input --placeholder "server_address?" )"
        if ! str_valid_ip_or_hostname "${server_address}" ; then
            printf "[${executor}] ${BRed}ERROR${Color_Off} - Invalid IP address or hostname!"
        else
            if [[ -z ${server_addresses+x} ]]; then
                declare -a server_addresses=( "${server_address}" )
            else
                server_addresses+=( "${server_address}" )
            fi
            gum confirm "Add more server addresses?" || break
        fi
    done

    while :; do
        local share_name="$( gum input --placeholder "share_name?" )"
        local share_mount_under="$( gum input --placeholder "share_mount_under?" )"
        local share_username="$( gum input --placeholder "share_username?" )"
        local share_password="$( gum input --password --placeholder "share_password?" )"
        local share_domain="$( gum input --placeholder "share_domain?" )"

        server_addresses_oneliner="$( str_join -d " " -- "${server_addresses[@]}" )"

        mountpoint = str(
            f"{pathlib.Path(f'{share_mount_under}').expanduser().resolve()}/{server_name}/{share_name}"
        )
        systemd_name = str(mountpoint).replace("/", "-").replace("-", "", 1)

        creds_dir = str(pathlib.Path(f"{credentials_directory}").expanduser().resolve())
        creds_file = str(
            pathlib.Path(f"{creds_dir}/{systemd_name}.creds").expanduser().resolve()
        )

        gum confirm "Add more shares?" || break
    done
}

function rfs_remove {
    if [[ ! -d "${rfs_cache}" ]]; then
        printf "[${executor}] ${BPurple}INFO${Color_Off} - Nothing to remove!"
    else
        mapfile -t selected_rfs < <( fd --glob '*.rfs' "${rfs_cache}" --exec-batch gum choose --no-limit --header "Select all rfs you wish to remove" )

        if [[ -z ${selected_rfs+x} || ${#selected_rfs[@]} -eq 0]]; then
            printf "[${executor}] ${BPurple}INFO${Color_Off} - Nothing to remove!"
        else
            for s_r in "${selected_rfs[@]}"; do

                mapfile -t extracted_info < <( cat "${s_r}" )
                for e_i in "${extracted_info[@]}"; do
                    case "${e_i}" in
                        "credentials_directory="*   ) local credentials_directory="$( cut -d '=' -f 2 )"    ;;
                        "execstart_script_dir="*    ) local execstart_script_dir="$( cut -d '=' -f 2 )"     ;;
                        "server_name="*             ) local server_name="$( cut -d '=' -f 2 )"              ;;
                        "share_name="*              ) local share_name="$( cut -d '=' -f 2 )"               ;;
                        "share_mount_under="*       ) local share_mount_under="$( cut -d '=' -f 2 )"        ;;
                    esac
                done

                mountpoint="$( expand_path "${share_mount_under}" )/${server_name}/${share_name}"
                systemd_name="$( str_replace_part -t '-' -r '' -c 1 -- $( str_replace_part -t '/' -r '-' -- "${mountpoint}" ) )"

                creds_dir="$( expand_path "${credentials_directory}" )"
                creds_file="$( expand_path "${creds_dir}/${systemd_name}.creds" )"

                printf "[${executor}] ${BPurple}INFO${Color_Off} - Disabling & removing files..."

                sudo systemctl disable --now "${systemd_name}.timer"
                printf "[${executor}] ${BPurple}INFO${Color_Off} - Disabled ${systemd_name}.timer"

                sudo systemctl stop "${systemd_name}.service"
                printf "[${executor}] ${BPurple}INFO${Color_Off} - Stopped ${systemd_name}.service"

                sudo systemctl stop "${systemd_name}.automount"
                printf "[${executor}] ${BPurple}INFO${Color_Off} - Stopped ${systemd_name}.automount"

                sudo systemctl stop "${systemd_name}.mount"
                printf "[${executor}] ${BPurple}INFO${Color_Off} - Stopped ${systemd_name}.mount"

                if [[ -f "/var/lib/${systemd_name}.env" ]]; then
                    sudo rm -vf "/var/lib/${systemd_name}.env"
                fi

                sudo rm -vf "$( expand_path "${execstart_script_dir}/${systemd_name}.sh" )"
                rm -vf "${creds_file}"
                sudo rm -vf "/etc/systemd/system/${systemd_name}".*
                sudo rm -vf "/etc/systemd/journald@${systemd_name}.conf"

                sudo systemctl daemon-reload
                printf "[${executor}] ${BPurple}INFO${Color_Off} - Completed systemctl daemon-reload"

                if [[ -f "/var/lib/${systemd_name}.rfs" ]]; then
                    sudo rm -vf "/var/lib/${systemd_name}.rfs"
                    printf "[${executor}] ${BPurple}INFO${Color_Off} - Removed registry file /var/lib/${systemd_name}.rfs"
                fi

                printf "[${executor}] ${BGreen}SUCCESS${Color_Off} - Done!"

            done
        fi
    fi
}

# ------------------------------------------------------------------------------

rfs_cache="/var/lib/rfs"

if [[ $# -gt 1 ]]; then
    printf "[${executor}] ${BRed}ERROR${Color_Off} - Invalid number of arguments!"
    print-usage
    exit 1
fi

if [[ $# -eq 1 ]]; then
    case "${1}" in
        -h | --help     )   print-usage
                            ;;
        -r | --remove   )   rfs_remove
                            ;;
    esac
else
    rfs_add
fi
