#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "fzf" )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - Command '${rc}' unavailable!?\n"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

function print_usage {
    cat << EOF
Usage: ${executor} [flags]

Setup CIFS/SMB remote shares for the current user on the local system.
Sudo permissions are needed for this.

Flags:
    -h, --help      Show all this.
    -r, --remove    Remove one or more shares from the system.

EOF
}

function rfs_add {
    # local server_name="$( gum input --header "Input server name" --placeholder "name" )"
    local server_name=""
    read -e -r -p "${BWhite}Enter server name:${Color_Off} " -i "my_nas_name" server_name && echo

    local server_address=""
    read -e -r -p "${BWhite}Enter a server address:${Color_Off} " -i "IPv4|IPv6|FQDN" server_address && echo
    # local server_address="$( gum input --header "Input a server address" --placeholder "IPv4 | IPv6 | FQDN" )"
    if ! str_valid_ip_or_hostname "${server_address}" ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - Invalid IP address or hostname!\n"
        exit 1
    fi

    local share_name=""
    read -e -r -p "${BWhite}Enter share name:${Color_Off} " -i "my_share_name" share_name && echo
    local share_username=""
    read -e -r -p "${BWhite}Enter share username:${Color_Off} " -i "username" share_username && echo
    local share_password=""
    read -e -r -s -p "${BWhite}Enter share password:${Color_Off} " -i "password" share_password && echo
    local share_domain=""
    read -e -r -p "${BWhite}Enter share domain:${Color_Off} " -i "domain" share_domain && echo

    # $( whoami ) or $( id -un ) for current user
    local local_user_uid=$( id -u ) # or $( id -u <username> ) for any other user than current
    local local_user_gid=$( id -g ) # or $( id -g <username> ) for any other user than current

    printf "[${executor}] ${BPurple}INFO${Color_Off} - Adding...\n"

    sudo mkdir -pv "/mnt/rfs/${server_name}/${share_name}"
    mkdir -pv "$HOME/rfs/${server_name}/${share_name}"
    ln -sinv "/mnt/rfs/${server_name}/${share_name}" "$HOME/rfs/${server_name}/${share_name}"

    sudo install -d -m 700 "${creds_store}"
    sudo sh -c "cat > /etc/rfs/${server_name}_${share_name}.creds" << EOF
username=${share_username}
password=${share_password}
domain=${share_domain}
EOF

    sudo chmod 600 "/etc/rfs/${server_name}_${share_name}.creds"
    sudo chown root:root "/etc/rfs/${server_name}_${share_name}.creds"

    # file_mode=0664,dir_mode=0755
    sudo sh -c 'tee -a /etc/fstab > /dev/null' << EOF
//${server_address}/${share_name} /mnt/rfs/${server_name}/${share_name} cifs _netdev,nofail,noauto,soft,vers=3.1.1,x-systemd.automount,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s,user,users,uid=${local_user_uid},gid=${local_user_gid},credentials=/etc/rfs/${server_name}_${share_name}.creds 0 0
EOF

    sudo systemctl daemon-reload

    printf "[${executor}] ${BGreen}SUCCESS${Color_Off} - Done!\n"
}

function rfs_remove {
    # $( whoami ) or $( id -un ) for current user
    local local_user_uid=$( id -u ) # or $( id -u <username> ) for any other user than current
    local local_user_gid=$( id -g ) # or $( id -g <username> ) for any other user than current

    mapfile -t available_rfs < <( grep -e 'cifs' -e "uid=${local_user_uid},gid=${local_user_gid}" /etc/fstab )
    if [[ -z ${available_rfs+x} || ${#available_rfs[@]} -eq 0 ]]; then
        printf "[${executor}] ${BPurple}INFO${Color_Off} - Nothing to remove!\n"
    else
        declare -a clean_available_rfs

        for arfs in "${available_rfs[@]}"; do
            local server_name="$( printf '%s\n' "${arfs}" | cut -d ' ' -f 2 | cut -d '/' -f 4 )"
            local server_address="$( printf '%s\n' "${arfs}" | cut -d ' ' -f 1 | cut -d '/' -f 3 )"
            local share_name="$( printf '%s\n' "${arfs}" | cut -d ' ' -f 1 | cut -d '/' -f 4 )"
            clean_available_rfs+=( "${share_name} @ ${server_name} @ ${server_address}" )
        done

        mapfile -t selected_rfs < <( printf '%s\n' "${clean_available_rfs[@]}" | fzf --multi )

        if [[ -z ${selected_rfs+x} || ${#selected_rfs[@]} -eq 0 ]]; then
            printf "[${executor}] ${BPurple}INFO${Color_Off} - Nothing to remove!\n"
        else
            for s_r in "${selected_rfs[@]}"; do

                if [[ "${s_r}" == "" ]]; then
                    printf "[${executor}] ${BRed}ERROR${Color_Off} - Invalid selection '${s_r}'\n"
                else

                    local share_name="$( printf '%s\n' "${s_r}" | cut -d '@' -f 1 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )"
                    local server_name="$( printf '%s\n' "${s_r}" | cut -d '@' -f 2 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )"
                    local server_address="$( printf '%s\n' "${s_r}" | cut -d '@' -f 3 | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )"

                    printf "[${executor}] ${BPurple}INFO${Color_Off} - Cleaning fstab...\n"
                    sed -i "/$( grep -e 'cifs' -e "uid=${local_user_uid},gid=${local_user_gid}" -e "${server_address}" -e "${share_name}" -e "${server_name}" -- /etc/fstab )/d" /etc/fstab # Remove specific line
                    sed -i '/^$/d' /etc/fstab # Remove all empty lines

                    sudo systemctl daemon-reload

                    printf "[${executor}] ${BPurple}INFO${Color_Off} - Removing creds...\n"
                    sudo rm -rfv "/etc/rfs/${server_name}_${share_name}.creds"

                    printf "[${executor}] ${BPurple}INFO${Color_Off} - Cleaning filesystem...\n"
                    if [ -z "$( ls -A "/etc/rfs" )" ]; then
                        printf "[${executor}] ${BPurple}INFO${Color_Off} - /etc/rfs is empty --> removing...\n"
                        sudo rm -rfv "/etc/rfs"
                    fi

                    # ls -A projects – list all the contents in the projects directory except for the . and .. entries.
                    # -z – this test parameter returns true if the output string is empty and false if not
                    if [ -z "$( ls -A "/mnt/rfs/${server_name}/${share_name}" )" ]; then
                        printf "[${executor}] ${BPurple}INFO${Color_Off} - /mnt/rfs/${server_name}/${share_name} is empty --> removing...\n"
                        rm -fv "$HOME/rfs/${server_name}/${share_name}"
                        sudo rm -rfv "/mnt/rfs/${server_name}/${share_name}"

                        if [ -z "$( ls -A "/mnt/rfs/${server_name}" )" ]; then
                            printf "[${executor}] ${BPurple}INFO${Color_Off} - /mnt/rfs/${server_name} is empty --> removing...\n"
                            sudo rm -rfv "/mnt/rfs/${server_name}"

                            if [ -z "$( ls -A "/mnt/rfs" )" ]; then
                                printf "[${executor}] ${BPurple}INFO${Color_Off} - /mnt/rfs is empty --> removing...\n"
                                sudo rm -rfv "/mnt/rfs"
                            fi
                        fi
                    else
                        printf "[${executor}] ${BRed}ERROR${Color_Off} - /mnt/rfs/${server_name}/${share_name} should be empty but is not --> ignoring...\n"
                    fi
                fi
            done
        fi

    fi
}

# ------------------------------------------------------------------------------

if [[ $# -eq 1 ]]; then
    case "${1}" in
        -h | --help     )   print_usage
                            ;;
        -r | --remove   )   rfs_remove
                            ;;
    esac
elif [[ $# -gt 1 ]]; then
    printf "[${executor}] ${BRed}ERROR${Color_Off} - Invalid number of arguments!\n"
    echo
    print_usage
    exit 1
else
    while :; do
        rfs_add
        echo
        # gum confirm "Add more shares?" || break
        local answer=""
        until [[ $answer =~ ^[Nn]$ || $answer =~ ^[Yy]$ ]]; do
            read -n 1 -r -p "Add more shares? (Y/N): " answer && echo
            case $answer in
                [Yy]* ) continue 2;;
                [Nn]* ) break 2;;
                * ) echo "Please answer Y or N.";;
            esac
        done
    done
fi
