#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "podman" "expand_path"  )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - '${rc}' not available!"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

app_name="syncthing"
base_image="docker.io/syncthing/syncthing:latest"

read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" config_location
config_location="$( expand_path "${config_location}" )"
read -e -p "Enter shares location:" -i "$HOME/syncthing" shares_location
shares_location="$( expand_path "${shares_location}" )"

# $( whoami ) or $( id -un ) for current user
local_user_uid=$( id -u ) # or $( id -u <username> ) for any other user than current
local_user_gid=$( id -g ) # or $( id -g <username> ) for any other user than current

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
mkdir -pv "$HOME/.config/containers/systemd"
mkdir -pv "${config_location}"
mkdir -pv "${shares_location}"

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
CONTAINER="
[Unit]
Description=${app_name} quadlet
Wants=network-online.target
After=network-online.target

[Service]
Restart=on-failure
TimeoutStartSec=900

[Container]
ContainerName=${app_name}
Image=${base_image}
AutoUpdate=registry
Network=host
UserNS=keep-id:uid=${local_user_uid},gid=${local_user_gid}
Volume=${config_location}:/var/syncthing/config:Z

# Folders to share
Volume=${shares_location}:/var/syncthing/shares:Z

[Install]
WantedBy=default.target
"
echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null

printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
systemctl --user daemon-reload

printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
systemctl --user restart "${app_name}"

# Start user services even when not logged in
loginctl enable-linger $USER

printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
# manually by calling 'podman auto-update'
# or automatically by enabling the relative systemd service:
systemctl enable --user --now podman-auto-update.timer
