#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "podman" "openssl" "expand_path" )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

function miniserve { (
    set ${SET_X:+-x} -eou pipefail
    fail=false
    for rc in "${required_cmds[@]}"; do
        if ! command -v "${rc}" &> /dev/null ; then
            printf "[${executor}] [ERROR] Command '${rc}' unavailable!?"
            fail=true
        fi
    done
    [[ "${fail}" == true ]] && exit 1
); }

if [ $# -lt 1 ]; then
    echo "Usage: ${executor} file"
    exit 1
fi

if [ -f "$1" ]; then
    case $1 in
        *.tar.xz)   if command -v tar 2>&1 >/dev/null; then
                        tar -xvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command 'tar' unavailable!?" && exit 1
                    fi ;;
        *.tar.bz2)  if command -v tar 2>&1 >/dev/null; then
                        tar -jxvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command 'tar' unavailable!?" && exit 1
                    fi ;;
        *.tar.gz)   if command -v tar 2>&1 >/dev/null; then
                        tar -zxvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command 'tar' unavailable!?" && exit 1
                    fi ;;
        *.bz2)      if command -v bunzip2 2>&1 >/dev/null; then
                        bunzip2 "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.dmg)      if command -v hdiutil 2>&1 >/dev/null; then
                        hdiutil mount "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.gz)       if command -v gunzip 2>&1 >/dev/null; then
                        gunzip "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.tar)      if command -v tar 2>&1 >/dev/null; then
                        tar -xvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.tbz2)     if command -v tar 2>&1 >/dev/null; then
                        tar -jxvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.tgz)      if command -v tar 2>&1 >/dev/null; then
                        tar -zxvf "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.zip)      if command -v unzip 2>&1 >/dev/null; then
                        unzip "$1"
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.pax)      if command -v pax 2>&1 >/dev/null; then
                        cat "$1" | pax -r
                    else
                        printf "[${executor}] [ERROR] Command '${rc}' unavailable!?" && exit 1
                    fi ;;
        *.pax.z)    if command -v uncompress 2>&1 >/dev/null; then
                        if command -v pax 2>&1 >/dev/null; then
                            uncompress "$1" --stdout | pax -r
                        else
                            printf "[${executor}] [ERROR] Command 'pax' unavailable!?" && exit 1
                        fi
                    else
                        printf "[${executor}] [ERROR] Command 'uncompress' unavailable!?" && exit 1
                    fi ;;
        *.rar)      if command -v 7z 2>&1 >/dev/null; then
                        7z x "$1"
                    else
                        printf "[${executor}] [ERROR] Command '7z' unavailable!?" && exit 1
                    fi ;;
        *.z)        if command -v uncompress 2>&1 >/dev/null; then
                        uncompress "$1"
                    else
                        printf "[${executor}] [ERROR] Command 'uncompress' unavailable!?" && exit 1
                    fi ;;
        *.7z)       if command -v 7z 2>&1 >/dev/null; then
                        7z x "$1"
                    else
                        printf "[${executor}] [ERROR] Command '7z' unavailable!?" && exit 1
                    fi ;;
        *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
    esac
else
    echo "'$1' is not a valid file" && exit 1
fi
