#!/usr/bin/env bash
set ${SET_X:+-x} -eou pipefail

#------------------------------------------------------------------------------
# ANSI escape code variables.
# ------------------------------------------------------------------------------

# Usage: printf "I ${Red}love${Color_Off} Stack Overflow\n"
# If you are using the echo command, be sure to use the -e flag to allow backslash escapes.
# echo -e "I ${Red}love${Color_Off} Stack Overflow"

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "podman" "ramalama" "str_is_url" "str_replace_part" )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - '${rc}' not available!"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

function print_usage {
    local msg="
usage: ${executor} -u URL -p PORT

options:
    -h      show this help message and exit
    -r      remove given model
    -u URL
            The character(s) or string(s) to target.
    -p PORT
            The character or string to use as the replacement.
    "
    echo "${msg}"
}

remove="false"
while getopts "ru:p:" flag; do
    case "${flag}" in
        r ) remove="true";;
        u ) url="${OPTARG}";;
        p ) port="${OPTARG}";;
        h ) print_usage && exit 0 ;;
        ? ) print_usage && exit 1 ;;
    esac
done

# unset or empty
if [[ -z ${url+x} || -z "${url}" ]]; then
    printf "[${executor}] ${BRed}ERROR${Color_Off} - A valid url is needed!\n"
    echo
    print_usage
    exit 1
fi

# unset or empty or not int
if [[ -z ${port+x} || -z "${port}" || ! "${port}" =~ ^[0-9]+$ ]]; then
    printf "[${executor}] ${BRed}ERROR${Color_Off} - A valid port is needed!\n"
    echo
    print_usage
    exit 1
fi

name="$( str_replace_part -t ':' '/' -r '_' -- "ramalama_${url}" )"

if [[ "${remove}" == "true" ]]; then

    # --force, -f
    # Remove running Quadlets (in case of uninstantiated template quadlets, stop its instances).
    # --ignore, -i
    # Do not error for Quadlets that do not exist.
    # --recursive
    # Required when removing applications (default false).
    podman quadlet rm --force --ignore --recursive -- "${name}"

    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Stop ramalama quadlet: %s\n" "${name}"
    # [[ "$( systemctl is-active "${name}" )" == "active" ]] && systemctl stop --user "${name}"

    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Remove quadlet container file...\n"
    # [[ -f "$HOME/.config/containers/systemd/${name}.container" ]] && rm -rfv "$HOME/.config/containers/systemd/${name}.container"

    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
    # systemctl --user daemon-reload

    printf "[${executor}] ${BPurple}INFO${Color_Off} - Remove ramalama model file...\n"
    ramalama rm --ignore -- "${url}" # ignore errors when specified Model does not exist

else

    mkdir -pv "$HOME/.config/quadlets/init/${name}"

    echo
    printf "[${executor}] ${BPurple}INFO${Color_Off} - Generating quadlet via ramalama for model: %s @ %s\n" "${url}" "${port}"
    ramalama serve --name "${name}" --port "${port}" --generate=quadlet:"$HOME/.config/quadlets/init/${name}" "${url}"

    podman quadlet install --replace --application=${name} "$HOME/.config/quadlets/init/${name}/"

    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
    # systemctl --user daemon-reload

    # printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable ramalama quadlet: %s\n" "${name}"
    # systemctl restart --user "${name}"

    loginctl enable-linger $USER

    printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable podman automatic updates...\n"
    # 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
    # manually by calling 'podman auto-update'
    # or automatically by enabling the relative systemd service:
    systemctl enable --user --now podman-auto-update.timer

fi
