#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------------------------

executor="${0##*/}"
executor_path="${BASH_SOURCE}"
while [ -L "${executor_path}" ]; do
    executor_dir="$(cd -P "$(dirname "${executor_path}")" >/dev/null 2>&1 && pwd)"
    executor_path="$(readlink "${executor_path}")"
    [[ ${executor_path} != /* ]] && executor_path="${executor_dir}/${executor_path}"
done
executor_path="$(readlink -f "${executor_path}")"
executor_dir="$(cd -P "$(dirname -- "${executor_path}")" >/dev/null 2>&1 && pwd)"

declare -a required_cmds=( "systemctl" "podman" "expand_path"  )

fail=false
for rc in "${required_cmds[@]}"; do
    if ! command -v "${rc}" &> /dev/null ; then
        printf "[${executor}] ${BRed}ERROR${Color_Off} - '${rc}' not available!"
        fail=true
    fi
done
[[ "${fail}" == true ]] && exit 1

# ------------------------------------------------------------------------------

app_name="syncthing"

read -e -p "Enter config location:" -i "$HOME/.config/quadlets/${app_name}" config_location
config_location="$( expand_path "${config_location}" )"
read -e -p "Enter shares location:" -i "$HOME/${app_name}" shares_location
shares_location="$( expand_path "${shares_location}" )"
read -e -p "Timezone:" -i "$(timedatectl show -P Timezone)" time_zone

# $( whoami ) or $( id -un ) for current user
local_user_uid=$( id -u ) # or $( id -u <username> ) for any other user than current
local_user_gid=$( id -g ) # or $( id -g <username> ) for any other user than current

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Ensuring required directories are present...\n"
mkdir -pv "$HOME/.config/containers/systemd"
mkdir -pv "${config_location}"
mkdir -pv "${shares_location}"

echo
printf "[${executor}] ${BPurple}INFO${Color_Off} - Creating quadlet...\n"
CONTAINER="
[Unit]
Description=${app_name} quadlet
Wants=network-online.target
After=network-online.target

[Container]
ContainerName=${app_name}
Image=docker.io/syncthing/syncthing:latest

# Podman automatic updates
AutoUpdate=registry

# User Namespace: Maps container user to host user
# This is crucial for Syncthing to have correct file permissions
UserNS=keep-id:uid=${local_user_uid},gid=${local_user_gid}

Environment=TZ=${time_zone}

# Use same hostname as host
HostName=$( hostname -s )

# Use host mode which is the recommended way to run Syncthing.
# It allows the service to easily discover other devices on your local network using UPnP/DLNA.
# Only works for a single instance of Syncthing.
Network=host

# Alternatively publish ports
# Application WebUI
# PublishPort=8384:8384
# Listening port (TCP)
# PublishPort=22000:22000/tcp
# Listening port (UDP)
# PublishPort=22000:22000/udp
# Protocol discovery
# PublishPort=21027:21027/udp

# Networking: Pasta is used by default in Podman 5+
# If you need to access host services (like Ollama on the host):
# AddHost=host.containers.internal:host-gateway

# Config
Volume=${config_location}:/var/syncthing/config:Z

# Default folder for shares
Volume=${shares_location}:/var/syncthing/shares:Z

# Maintenance & Logging
# Log to JSON files
LogDriver=k8s-file
PodmanArgs=--log-opt=max-size=10m --log-opt=max-file=3

[Service]
Restart=unless-stopped
RestartSec=5
# Give image pulls/builds enough time during startup
TimeoutStartSec=900

[Install]
WantedBy=multi-user.target default.target
"
echo "${CONTAINER}" | tee "$HOME/.config/containers/systemd/${app_name}.container" > /dev/null

printf "[${executor}] ${BPurple}INFO${Color_Off} - Reload systemd...\n"
systemctl --user daemon-reload

printf "[${executor}] ${BPurple}INFO${Color_Off} - Start/enable quadlet...\n"
systemctl --user restart "${app_name}"

# Start user services even when not logged in
loginctl enable-linger $USER

printf "[${executor}] ${BPurple}INFO${Color_Off} - Enable automatic podman updates...\n"
# 'AutoUpdate=registry' in the systemd definition allows the container to be auto-updated,
# manually by calling 'podman auto-update'
# or automatically by enabling the relative systemd service:
systemctl enable --user --now podman-auto-update.timer

printf "[${executor}] ${BGreen}DONE${Color_Off} - Check logs with: podman logs -tf ${app_name}\n"
